name: 'env-req-parser'
description: 'Parses an Environment Request Issue into output parameters that can be used for creating the environments.'
author: 'nkpatterson'
runs:
  using: 'node12'
  main: './env-req-parser.js'
outputs:
  appName:
    description: Name of app as input by requester
  armTemplate:
    description: 'Refers to the ARM templates in the /templates directory [vmss-windows-nat,web-app-sql-database,function-app]'
  environmentType:
    description: 'Environment type can be [Development, Staging, Production]'
  approved:
    description: 'Validates that the issue has an approved label applied'